"""Shared, dependency-free type layer for Il Dottore (models, protocols, enums).

Leaf of the import graph: imports nothing else in-repo (stdlib + ``pydantic`` only).
"""

from __future__ import annotations

from ildottore.shared.enums import (
    Band,
    Capability,
    Category,
    EvaluatorLogic,
    EvaluatorType,
    InconclusiveReason,
    ReportFormat,
    RequiresCapability,
    ScanBand,
    Severity,
    TargetType,
    VerdictStatus,
)
from ildottore.shared.models import (
    Attack,
    AttackSpec,
    Attempt,
    Budget,
    Capabilities,
    EvalContext,
    EvaluatorConfig,
    Evidence,
    EvidenceRef,
    Finding,
    FingerprintEvidence,
    FingerprintGuess,
    FixtureCase,
    Fixtures,
    MitreAtlas,
    ModelFingerprint,
    ModelRequest,
    ModelResponse,
    PlanBudgets,
    PlanSelection,
    PlanSkip,
    RiskScore,
    Sampling,
    Scoring,
    Setup,
    SetupDoc,
    Target,
    TestPlan,
    TestRun,
    TestRunSummary,
    TokenLogprob,
    Verdict,
)
from ildottore.shared.protocols import (
    Evaluator,
    EvidenceStore,
    Mutator,
    Reporter,
    RiskScorer,
    RunStore,
    TargetAdapter,
)
from ildottore.shared.schema_export import Pack, Suite, SuiteEntry, export_schemas

__all__ = [
    "Attack",
    "AttackSpec",
    "Attempt",
    "Band",
    "Budget",
    "Capabilities",
    "Capability",
    "Category",
    "EvalContext",
    "Evaluator",
    "EvaluatorConfig",
    "EvaluatorLogic",
    "EvaluatorType",
    "Evidence",
    "EvidenceRef",
    "EvidenceStore",
    "Finding",
    "FingerprintEvidence",
    "FingerprintGuess",
    "FixtureCase",
    "Fixtures",
    "InconclusiveReason",
    "MitreAtlas",
    "ModelFingerprint",
    "ModelRequest",
    "ModelResponse",
    "Mutator",
    "Pack",
    "PlanBudgets",
    "PlanSelection",
    "PlanSkip",
    "ReportFormat",
    "Reporter",
    "RequiresCapability",
    "RiskScore",
    "RiskScorer",
    "RunStore",
    "Sampling",
    "ScanBand",
    "Scoring",
    "Setup",
    "SetupDoc",
    "Severity",
    "Suite",
    "SuiteEntry",
    "Target",
    "TargetAdapter",
    "TargetType",
    "TestPlan",
    "TestRun",
    "TestRunSummary",
    "TokenLogprob",
    "Verdict",
    "VerdictStatus",
    "export_schemas",
]
